/**
 * Algorithm to obtain pentagonal numbers.
 *
 * Pentagonal numbers are generated by the formula, 
 * Pn=n(3n−1)/2
 *
 * @class Lychrel
 */

Pentagonal = function() {

	Algorithm.call(this);
};

Pentagonal.prototype = new Algorithm();

/**
 * @param {Integer} n 
 * @return {Integer}
 * @method solve
 * @public
 */

Pentagonal.prototype.solve = function(n) {
  return ((n * (3*n-1)) / 2);
};

// Expose the object
exports.Pentagonal = Pentagonal;
